### ISSUE TITLE
Further ideas and enhancements

### ISSUE THREAD

**Issue by SofiaMalmsten** [ArchitudeSweden/FileMaker_Timelines#60]
- [ ] Background as a slider (https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/54)
- [ ] Visually differentiate the different regions in the timeline (https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/52)
- [ ] Introduce sub-groups for the categories (https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/30)
- [ ] Add Q1-Q4 header (https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/39)
- [ ] Save timeline as interactive PDF (https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/48)
- [ ] Move styles from HTML to CSS https://github.com/ArchitudeSweden/FileMaker_Timelines/issues/49
- [x] Add custom time bar

**Comment by SofiaMalmsten** [comment]
Will Close this issue for now. We can reopen it later if we need to do that
